### PR TITLE
Electrons from foil fix

### PR DESCRIPTION
**Pull request by matteoceschia**
Hi @pfranchini , could you please review this issue? I think it's just a typo in calling one of TrackDetails methods, it should work fine.

### CODE REVIEW

**Comment by pfranchini** [comment]
I assume I might have wanted to keep the backwards compatibility, since vertices_on_foil becomes vertices_in tracker. 
Considering the above comment
`          // And whether or not they are from the foil      `
was wrong before (were vertices from tracker), is still wrong now (are *only* vertices from foil).
Shall we change the comment?

**Comment by pfranchini** [comment]
@cherylepatrick  should we just change the comment to
```
//And if are from the foil 
```
on top of the commit above?

**Comment by cherylepatrick** [comment]
Hiya both - yeah, I thought you were probably maintaining backwards compatibility, but I *think* it was probably wrong in the first place. I really can't remember why I had it the way I did. I did wonder a bit if it might be because of something we were doing for a while where we were experimenting with projecting tracks back to the foil if they ended close to it - but I don't think anyone is using that for active analyses at the moment anyway. I think we should probably do Matteo's change plus Paolo's clarifying comment.

Also on line 466, there is  `if (trackDetails.HasTrackerVertex()) foilAlphaCount++;` - I think that probably also wants to be changed to HasFoilVertex(). Do you agree?

**Comment by pfranchini** [comment]
> Hiya both - yeah, I thought you were probably maintaining backwards compatibility, but I _think_ it was probably wrong in the first place. I really can't remember why I had it the way I did. I did wonder a bit if it might be because of something we were doing for a while where we were experimenting with projecting tracks back to the foil if they ended close to it - but I don't think anyone is using that for active analyses at the moment anyway. I think we should probably do Matteo's change plus Paolo's clarifying comment.

Ok, not sure either about it.

> Also on line 466, there is `if (trackDetails.HasTrackerVertex()) foilAlphaCount++;` - I think that probably also wants to be changed to HasFoilVertex(). Do you agree?

Yes this should probably to be changed as well.

**Review by cherylepatrick — APPROVED** [review]
Looks good Matteo, thank you!

**Pull request merged**
