### PR TITLE
Allow SensitivityModule to run with both Falaise 4.X and develop

### PR DESCRIPTION
**Pull request by drbenmorgan**
To allow the integration of SensitivityModule in Falaise, this is a simple update to allow it to compile against/use the data model API from both Falaise 4 and the current develop branch.

It's a compile time test and has no effect on the use/interface of/to SensitivityModule. The behaviour and outputs should remain unchanged, as the same results are pulled from the data, just through the appropriate member functions in the two APIs.

An additional CI job has been added to test against both the develop and released versions of Falaise.

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Everything looked to compile ok., but not sure why tests failed. Have made the output more verbose to check.

**Comment by drbenmorgan** [comment]
@cherylepatrick, @willquinn, I've fixed the test failures, so all ready for you to review and merge!

**Comment by cherylepatrick** [comment]
Thanks @drbenmorgan - pretty busy right now but I will get to it ASAP

**Comment by cherylepatrick** [comment]
Sorry for slow response on this but finally testing it now. Works fine on 4.0.1 (CCLyon/singularity) and  4.0.2 (90dd7f63-dirty) / Mac (what I have lying around on my computer which I think needs the new format... but I will test on develop also).

**Comment by cherylepatrick** [comment]
I don't know what I am doing wrong, but I can't get it to work on the dev Falaise that's on CCLyon - can anyone else? I followed Yves' instructions:
```
source /sps/nemo/sw/config/supernemo_profile_1.bash
load_supernemo_setup_pro
load_falaise_setup_dev
```
Which gives me
```
* Falaise : 4.0.3 (f492f8f1)
* Bayeux  : 3.4.2
* Boost   : 106900
* Geant4  : 9.6.4
```
I re-cmaked but `make` is still finding the old versions of variable names. Do I need to do something to get it recognise that it needs to pick the new ones? I guess "NEW_DATAMODEL_API" needs to get set somewhere?

**Comment by cherylepatrick** [comment]
Hi @drbenmorgan - I still can't get this to work. I hoped the instructions Paolo gave Hamzah would fix the problem, but I think they were actually just what I was doing anyway.

I've checked out this branch, and set up Yves' dev setup:
```
[cpatrick@cca007 build]$ /sps/nemo/sw/Falaise/install-devel/bin/flsimulate --version
flsimulate 4.0.3 (f492f8f1)

Copyright (C) 2013-2018 SuperNEMO Collaboration

flsimulate uses the following external libraries:
* Falaise : 4.0.3 (f492f8f1)
* Bayeux  : 3.4.2
* Boost   : 106900
* Geant4  : 9.6.4
```
I think I should be using that to build: `cmake -DCMAKE_PREFIX_PATH=/sps/nemo/sw/Falaise/install-devel ..`

But when I try to `make`, it doesn't work: 

```
[ 33%] Building CXX object CMakeFiles/SensitivityModule.dir/SensitivityModule.cpp.o
In file included from /sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include/boost/random/detail/integer_log2.hpp:19:0,
                 from /sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include/boost/random/detail/int_float_pair.hpp:26,
                 from /sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include/boost/random/normal_distribution.hpp:28,
                 from /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/include/bayeux/geomtools/blur_spot.h:24,
                 from /sps/nemo/sw/Falaise/install-devel/include/falaise/snemo/datamodels/particle_track.h:23,
                 from /sps/nemo/sw/Falaise/install-devel/include/falaise/snemo/datamodels/particle_track_data.h:30,
                 from /pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.h:31,
                 from /pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:1:
/sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include/boost/pending/integer_log2.hpp:7:59: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
 BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
                                                           ^
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp: In member function 'virtual dpp::base_module::process_status SensitivityModule::process(datatools::things&)':
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:302:61: error: 'collection_type' in 'class snemo::datamodel::calibrated_calorimeter_hit' does not name a type
         const snemo::datamodel::calibrated_calorimeter_hit::collection_type& calHits = calData.calibrated_calorimeter_hits();
                                                             ^~~~~~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:305:33: error: 'calHits' was not declared in this scope
         for (const auto& iHit : calHits) {
                                 ^~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:305:33: note: suggested alternative: 'calData'
         for (const auto& iHit : calHits) {
                                 ^~~~~~~
                                 calData
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:340:57: error: 'collection_type' in 'class snemo::datamodel::calibrated_tracker_hit' does not name a type
         const snemo::datamodel::calibrated_tracker_hit::collection_type& trackerHits = calData.calibrated_tracker_hits();
                                                         ^~~~~~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:343:33: error: 'trackerHits' was not declared in this scope
         for (const auto& iHit : trackerHits) {
                                 ^~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:343:33: note: suggested alternative: 'TrackDetails'
         for (const auto& iHit : trackerHits) {
                                 ^~~~~~~~~~~
                                 TrackDetails
```
And plenty more in the same vein... can paste more if helpful but I'm guessing it's just not picking up on the new version? Am I missing something silly?

**Comment by drbenmorgan** [comment]
Hi @cherylepatrick, apologies, this slipped my mind. Can you try a fresh build (i.e. delete the build directory and create a new one) and post the output of:

1) Running cmake (it should print something about the detected data model)
2) `make VERBOSE=1` (this will have the details of what it thinks it should doing regards the data model)

**Comment by cherylepatrick** [comment]
Happy New Year @drbenmorgan ! Well, it's sure been a while but new year, new start! Let's try and get this sorted out. Can't really remember where we'd got to but here goes nothin'... any ideas what I'm doing wrong here? Does the boost stuff matter? Not quite sure what to look for...

```
[cpatrick@cca007 build]$ cmake -DCMAKE_PREFIX_PATH=/sps/nemo/sw/Falaise/install-devel  ..
-- Falaise_RESOURCE_DIR = /sps/nemo/sw/Falaise/install-devel/share/Falaise-4.0.3/resources
-- Searching Bayeux 3.4.2 from /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2 ...
-- Searching Boost 1.69 from /sps/nemo/sw/BxCppDev/opt/boost-1.69.0 ...
CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


CMake Warning at /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /pbs/software/centos-7-x86_64/cmake/3.11.0/share/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/lib64/cmake/Bayeux-3.4.2/BayeuxConfig.cmake:119 (find_package)
  /sps/nemo/sw/Falaise/install-devel/lib64/cmake/Falaise-4.0.3/FalaiseConfig.cmake:91 (find_package)
  CMakeLists.txt:6 (find_package)


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   serialization
--   iostreams
--   program_options
--   regex
--   thread
--   thread
--   chrono
--   date_time
--   atomic
-- Found GSL: /sps/nemo/sw/BxCppDev/opt/gsl-2.4/include (found suitable version "2.4", minimum required is "2.4") 
-- Configuring done
-- Generating done
-- Build files have been written to: /pbs/home/c/cpatrick/SensitivityModule/build
[cpatrick@cca007 build]$ make VERBOSE=1
/pbs/software/centos-7-x86_64/cmake/3.11.0/bin/cmake -H/pbs/home/c/cpatrick/SensitivityModule -B/pbs/home/c/cpatrick/SensitivityModule/build --check-build-system CMakeFiles/Makefile.cmake 0
/pbs/software/centos-7-x86_64/cmake/3.11.0/bin/cmake -E cmake_progress_start /pbs/home/c/cpatrick/SensitivityModule/build/CMakeFiles /pbs/home/c/cpatrick/SensitivityModule/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/pbs/home/c/cpatrick/SensitivityModule/build'
make -f CMakeFiles/SensitivityModule.dir/build.make CMakeFiles/SensitivityModule.dir/depend
make[2]: Entering directory `/pbs/home/c/cpatrick/SensitivityModule/build'
cd /pbs/home/c/cpatrick/SensitivityModule/build && /pbs/software/centos-7-x86_64/cmake/3.11.0/bin/cmake -E cmake_depends "Unix Makefiles" /pbs/home/c/cpatrick/SensitivityModule /pbs/home/c/cpatrick/SensitivityModule /pbs/home/c/cpatrick/SensitivityModule/build /pbs/home/c/cpatrick/SensitivityModule/build /pbs/home/c/cpatrick/SensitivityModule/build/CMakeFiles/SensitivityModule.dir/DependInfo.cmake --color=
Dependee "/pbs/home/c/cpatrick/SensitivityModule/build/CMakeFiles/SensitivityModule.dir/DependInfo.cmake" is newer than depender "/pbs/home/c/cpatrick/SensitivityModule/build/CMakeFiles/SensitivityModule.dir/depend.internal".
Dependee "/pbs/home/c/cpatrick/SensitivityModule/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/pbs/home/c/cpatrick/SensitivityModule/build/CMakeFiles/SensitivityModule.dir/depend.internal".
Scanning dependencies of target SensitivityModule
make[2]: Leaving directory `/pbs/home/c/cpatrick/SensitivityModule/build'
make -f CMakeFiles/SensitivityModule.dir/build.make CMakeFiles/SensitivityModule.dir/build
make[2]: Entering directory `/pbs/home/c/cpatrick/SensitivityModule/build'
[ 33%] Building CXX object CMakeFiles/SensitivityModule.dir/SensitivityModule.cpp.o
/pbs/software/centos-7-x86_64/gcc/7.3.0/bin/g++  -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -DSensitivityModule_EXPORTS -isystem /sps/nemo/sw/BxCppDev/opt/camp-0.8.4/include -isystem /sps/nemo/sw/Falaise/install-devel/include -isystem /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/include -isystem /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/include/bayeux -isystem /sps/nemo/sw/BxCppDev/opt/root-6.16.00/include/root -isystem /sps/nemo/sw/BxCppDev/opt/clhep-2.1.3.1/lib/CLHEP-2.1.3.1/../../include -isystem /sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include -isystem /sps/nemo/sw/BxCppDev/opt/gsl-2.4/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/./mkspecs/linux-g++ -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSvg -isystem /sps/nemo/sw/BxDecay0/install-1.0.5/include  -fPIC   -std=gnu++11 -o CMakeFiles/SensitivityModule.dir/SensitivityModule.cpp.o -c /pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp
In file included from /sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include/boost/random/detail/integer_log2.hpp:19:0,
                 from /sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include/boost/random/detail/int_float_pair.hpp:26,
                 from /sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include/boost/random/normal_distribution.hpp:28,
                 from /sps/nemo/sw/BxCppDev/opt/bayeux-3.4.2/include/bayeux/geomtools/blur_spot.h:24,
                 from /sps/nemo/sw/Falaise/install-devel/include/falaise/snemo/datamodels/particle_track.h:23,
                 from /sps/nemo/sw/Falaise/install-devel/include/falaise/snemo/datamodels/particle_track_data.h:30,
                 from /pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.h:31,
                 from /pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:1:
/sps/nemo/sw/BxCppDev/opt/boost-1.69.0/include/boost/pending/integer_log2.hpp:7:59: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
 BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
                                                           ^
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp: In member function 'virtual dpp::base_module::process_status SensitivityModule::process(datatools::things&)':
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:302:61: error: 'collection_type' in 'class snemo::datamodel::calibrated_calorimeter_hit' does not name a type
         const snemo::datamodel::calibrated_calorimeter_hit::collection_type& calHits = calData.calibrated_calorimeter_hits();
                                                             ^~~~~~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:305:33: error: 'calHits' was not declared in this scope
         for (const auto& iHit : calHits) {
                                 ^~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:305:33: note: suggested alternative: 'calData'
         for (const auto& iHit : calHits) {
                                 ^~~~~~~
                                 calData
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:340:57: error: 'collection_type' in 'class snemo::datamodel::calibrated_tracker_hit' does not name a type
         const snemo::datamodel::calibrated_tracker_hit::collection_type& trackerHits = calData.calibrated_tracker_hits();
                                                         ^~~~~~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:343:33: error: 'trackerHits' was not declared in this scope
         for (const auto& iHit : trackerHits) {
                                 ^~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:343:33: note: suggested alternative: 'TrackDetails'
         for (const auto& iHit : trackerHits) {
                                 ^~~~~~~~~~~
                                 TrackDetails
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:363:50: error: 'const class snemo::datamodel::tracker_clustering_data' has no member named 'has_default_solution'; did you mean 'has_default'?
     bool clusterHasDefaultSolution = clusterData.has_default_solution();
                                                  ^~~~~~~~~~~~~~~~~~~~
                                                  has_default
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:372:78: error: 'const class snemo::datamodel::tracker_clustering_data' has no member named 'get_default_solution'; did you mean 'get_default'?
         snemo::datamodel::tracker_clustering_solution solution = clusterData.get_default_solution();
                                                                              ^~~~~~~~~~~~~~~~~~~~
                                                                              get_default
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:373:62: error: 'cluster_col_type' in 'class snemo::datamodel::tracker_clustering_solution' does not name a type
         const snemo::datamodel::tracker_clustering_solution::cluster_col_type& clusters = solution.get_clusters();
                                                              ^~~~~~~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:376:37: error: 'clusters' was not declared in this scope
         for (const auto& iCluster : clusters)
                                     ^~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:376:37: note: suggested alternative: 'iCluster'
         for (const auto& iCluster : clusters)
                                     ^~~~~~~~
                                     iCluster
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:383:45: error: 'const class snemo::datamodel::tracker_cluster' has no member named 'get_number_of_hits'
           bool hasAtLeastMinHits = (cluster.get_number_of_hits() >= minHitsInCluster);
                                             ^~~~~~~~~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:416:39: error: 'const class snemo::datamodel::particle_track_data' has no member named 'has_particles'; did you mean 'hasParticles'?
     bool havePTDParticles = trackData.has_particles();
                                       ^~~~~~~~~~~~~
                                       hasParticles
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:424:52: error: 'particle_collection_type' in 'class snemo::datamodel::particle_track_data' does not name a type
       const snemo::datamodel::particle_track_data::particle_collection_type& particles = trackData.get_particles();
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:427:36: error: 'particles' was not declared in this scope
       for (const auto& iParticle : particles) {
                                    ^~~~~~~~~
/pbs/home/c/cpatrick/SensitivityModule/SensitivityModule.cpp:427:36: note: suggested alternative: 'iParticle'
       for (const auto& iParticle : particles) {
                                    ^~~~~~~~~
                                    iParticle
make[2]: *** [CMakeFiles/SensitivityModule.dir/SensitivityModule.cpp.o] Error 1
make[2]: Leaving directory `/pbs/home/c/cpatrick/SensitivityModule/build'
make[1]: *** [CMakeFiles/SensitivityModule.dir/all] Error 2
make[1]: Leaving directory `/pbs/home/c/cpatrick/SensitivityModule/build'
make: *** [all] Error 2
[cpatrick@cca007 build]$ /sps/nemo/sw/Falaise/install-devel/bin/flsimulate --version
flsimulate 4.0.3 (f492f8f1)

Copyright (C) 2013-2018 SuperNEMO Collaboration

flsimulate uses the following external libraries:
* Falaise : 4.0.3 (f492f8f1)
* Bayeux  : 3.4.2
* Boost   : 106900
* Geant4  : 9.6.4
```

**Comment by drbenmorgan** [comment]
Hi @cherylepatrick, I've updated this with the master changes to `SensitivityModule` and got the CI to work fully. It's confirmed as compiling and working with a _very_ basic sim->reco->SM chain and Falaise 4.0.3 (tag release) and the current tip of the [Falaise develop branch](https://github.com/SuperNEMO-DBD/Falaise/commit/f0eac8618b7827bc878d32a53e459e35e77790b9), so ready for any further tests/review on your side.

**Review by cherylepatrick — APPROVED** [review]
Well it was a process, but we got there in the end! Thanks lots @drbenmorgan !

**Pull request merged**
