### PR TITLE
Iterate CI workflow

### PR DESCRIPTION
**Pull request by drbenmorgan**
Initial commit/merge highlighted some issues, resolve them here.

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Hi @cherylepatrick, this is just about working - the build fails due to the known changes in Falaise API, but the CI itself is working fine. I can also add a job that would test against the current Falaise production release if you wanted to ensure back compatibility?

When it's ready for merge, I'd recommend choosing the "Squash and Merge" option from the "Merge pull request" drop down. That'll only introduce one commit rather than my iterative hacks!

**Comment by cherylepatrick** [comment]
Thank you @drbenmorgan ! What, if anything, do I need to do to test it? Or do I just click squash and let it do what it does?

**Comment by drbenmorgan** [comment]
Hi @cherylepatrick, nothing really to test here as the build's expected to fail. I think just squash and merge, then see what happens to #29. I'm not sure if that will be tested with this, or if it will need to be rebased onto master, let's see.

**Comment by cherylepatrick** [comment]
Squashing! Thanks Ben!

**Comment by drbenmorgan** [comment]
Hi @cherylepatrick, sorry, looks like the squash/merge wasn't completed? I can do so if you're happy for me to do so!

**Comment by cherylepatrick** [comment]
Dude I am so bad at GitHub :( I thought I did it!

**Comment by drbenmorgan** [comment]
Too many buttons! Thanks for the merge!

**Comment by cherylepatrick** [comment]
I think you have to select it to turn it into a button and then click the button. But I did not realise that :)

**Pull request merged**
