### PR TITLE
Make SensitivityModule compile with new PTD changes

### PR DESCRIPTION
**Pull request by cherylepatrick**
Updated SensitivityModule so that it will build against the latest Falaise 4 version with new syntax for various parts of the data model (issue #28 ). Test should be to check that branches are filled and correspond to the right info (compare with flvisualize). This should include events with electron, positron, gamma and alpha candidates. No need to test calculated quantities - those didn't change - it's things like electron and gamma energies & charges; cluster, track and hit counts; delayed hit times. I also fixed a bug in the true lower particle type so can you sanity check that too.
@willquinn would you be able to test this for me?

### CODE REVIEW

**Comment by drbenmorgan** [comment]
@cherylepatrick, would having CI setup here be useful? It would be a little kludgy for now since we'd have to build Falaise from source and could only use CentOS7, but I can get it set up if that would help.

**Comment by cherylepatrick** [comment]
I think maybe yes! At least we would have caught the build problem, if nothing else. Thanks!

**Comment by drbenmorgan** [comment]
O.k., I'll try a separate PR with it in. Once that's merged, this _should_ pick it up automatically.

**Comment by pfranchini** [comment]
Hi Cheryl, would mind considering also merging what proposed in #26 and with a pull request in #27? Thanks

**Comment by cherylepatrick** [comment]
@pfranchini Sure!

**Comment by drbenmorgan** [comment]
Hi @cherylepatrick, o.k., whilst the CI is now on the `master` branch, this hasn't been picked up on this PR. I thought it might do it automatically, but looks like you'll need to rebase the `PTDBankNewNames` onto the updated `master`. That should be possible in your clone by doing

```console
$ git checkout PTDBankNewNames
$ git fetch origin
$ git rebase origin/master
... it's possible you might get conflicts here from Paolo's PR...
... fix them if needed...
$ git push -f origin PTDBankNewNames
```

The CI should then trigger...

**Comment by cherylepatrick** [comment]
Haha, thanks for looking after me Ben. Did that and had a (very) quick test of Paolo's stuff in the new branch.

**Comment by drbenmorgan** [comment]
YES! It's working!

**Comment by drbenmorgan** [comment]
... and even went ✅ first time!

**Comment by cherylepatrick** [comment]
All checks have passed!

**Comment by drbenmorgan** [comment]
So all good to add extra fixes/review/merge at your convenience!

**Comment by cherylepatrick** [comment]
Great! Will is doing some testing so I will await his say-so and then merge :)

**Comment by cherylepatrick** [comment]
Because everything is trouble... for both me and Will, this crashes on CCLyon (on the same input file, so that isn't the problem). Runs fine on my mac. @drbenmorgan - is this a boost version issue? We also don't have exactly the same falaise versions but it looks like a boost error? And do you know how we might update boost?
```
/pbs/home/c/cpatrick(0)>flreconstruct -i rec100.brio -p /pbs/home/c/cpatrick/SensitivityModuleMaster/SensitivityModule/build/SensitivityModuleExample.conf 
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for brio/detail/TArrayCMod.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for brio/detail/brio_record.h
   requested to autoload type brio_record
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
Aborted
```
On Lyon I am running
flreconstruct uses the following external libraries:
* Falaise : 4.0.2 (88407f0c-dirty)
* Bayeux  : 3.4.1
* Boost   : 106300

On the mac:
flreconstruct uses the following external libraries:
* Falaise : 4.0.2 (90dd7f63-dirty)
* Bayeux  : 3.4.1
* Boost   : 106900
Will on Lyon has 4.0.3 falaise but the same 106300 boost. And I think that boost might come from Yves `/sps/nemo/scratch/ylemiere/soft_simu/simulation/cadfaelbrew`

Any ideas? Should I try and match the falaise version I have on the mac? I think I got this version during a recent tutorial session and am not really sure of why I have the one I have... (I have the one I have on the mac cos I got it to fix the flvisualize bug the other week)

**Comment by drbenmorgan** [comment]
I suspect you're running into the issue outlined here: https://github.com/BxCppDev/Bayeux/issues/30

If you've generated the file with Boost 1.69, then there's no guarantee it can be read with 1.63. Falaise version shouldn't matter, just Boost.

**Comment by cherylepatrick** [comment]
Ah! Let's try a new file from scratch then... thanks!

**Comment by drbenmorgan** [comment]
It _should_ work if you generate with a Falaise/Bayeux compiled against Boost 1.63, then read with Boost 1.69. If not, then we're in _real_ trouble.

**Comment by cherylepatrick** [comment]
Just simulated/reconstructed on the same Falaise as I've set up SensitivityModule on on CCLyon, and SensitivityModule runs fine. Bad news is that the reconstruction through the official pipeline failed after 29/100 events but... that's not a SensitivityModule bug, so one thing at a time. Pretty sure it's issue #199 as the first unreconstructed event has a gamma veto hit.

**Review by willquinn — APPROVED** [review]
Build succeeded on CCLyon with a working version of Falaise 4.0.3.

Testing on a reconstructed 2nubb .brio file (with a PTD bank). Output sensitivity ntuple contains information coherent with the information displayed in flvisualise. For example I tested the following:

- number of clusters
- number of tracks
- number of associated tracks
- electron energies
- electron charges

All passed inspection.

**Pull request merged**
